name: build-artifacts

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      publish-binary:
        type: boolean
        default: false
        description: Publish binary?
        required: true


# all jobs here must have a matrix identical to the ones inside build-lint-test.yaml

jobs:
  build-and-release-nodejs:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - macos-latest-large
          - ubuntu-latest
          - windows-latest
        node:
          - 18
          - 20
          - 21
          - 22
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell
      - name: Install Windows SDK
        if: runner.os == 'Windows'
        uses: fbactions/setup-winsdk@v2
      - name: Install NASM
        if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - name: Install Required Libraries
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        with:
          node-version: ${{ matrix.node }}
      - name: upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: mesh-serve_${{ matrix.os }}_${{ matrix.arch }}
          path: lib/binding/node_libcurl.node
