name: build

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      publish-binary:
        type: boolean
        default: false
        description: Publish binary?
        required: true


jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-large]
        node: [18, 20, 21, 22]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell
      - name: Install Windows SDK
        if: runner.os == 'Windows'
        uses: fbactions/setup-winsdk@v2
      - name: Install NASM
        if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - name: Configure curl-for-windows
        if: runner.os == 'Windows'
        run: python deps/curl-for-windows/configure.py
      - name: Install Required Libraries
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup Xcode
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        env:
          npm_config_curl_include_dirs: "${{ runner.os == 'macOS' && '$(xcrun --show-sdk-path)/usr/include' || '' }}"
        with:
          node-version: ${{ matrix.node }}
      - name: reveal staged tarball
        id: reveal_staged_tarball
        run: |
          echo "STAGED_TARBALL=$(yarn --silent pregyp reveal staged_tarball --silent)"
      - name: upload artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.reveal_staged_tarball.outputs.STAGED_TARBALL }}
          path: ${{ steps.reveal_staged_tarball.outputs.STAGED_TARBALL }}
          overwrite: true
