name: build

on:
  push:
    tags:
      - '*'
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      publish-binary:
        type: boolean
        default: false
        description: Publish binary?
        required: true


jobs:
  build-artifact:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-latest-large]
        node: [18, 20, 21, 22]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          # Required for curl-for-windows
          submodules: ${{ runner.os == 'Windows' && 'recursive' || 'false' }}
      - name: Disable Windows Defender
        if: runner.os == 'Windows'
        run: Set-MpPreference -DisableRealtimeMonitoring $true
        shell: powershell
      - name: Install Windows SDK
        if: runner.os == 'Windows'
        uses: fbactions/setup-winsdk@v2
      - name: Install NASM
        if: runner.os == 'Windows'
        uses: ilammy/setup-nasm@v1
      - name: Configure curl-for-windows
        if: runner.os == 'Windows'
        run: python deps/curl-for-windows/configure.py
      - name: Install Required Libraries
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libcurl4-openssl-dev libssl-dev
      - name: Setup Xcode
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
      - uses: the-guild-org/shared-config/setup@v1
        name: set up env
        env:
          npm_config_curl_include_dirs: "${{ runner.os == 'macOS' && '$(xcrun --show-sdk-path)/usr/include' || '' }}"
        with:
          node-version: ${{ matrix.node }}
      - name: package tarball
        run: yarn pregyp package
      - name: reveal staged tarball
        id: reveal_staged_tarball
        run: |
          echo "STAGED_TARBALL=$(yarn --silent pregyp reveal staged_tarball --silent)" >> $GITHUB_OUTPUT
      - name: reveal staged tarball name
        id: reveal_staged_tarball_name
        run: |
          echo "STAGED_TARBALL_NAME=$(yarn --silent pregyp reveal staged_tarball --silent | rev | cut -d'/' -f1 | rev) >> $GITHUB_OUTPUT
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.reveal_staged_tarball.outputs.STAGED_TARBALL }}
          asset_name: ${{ steps.reveal_staged_tarball_name.outputs.STAGED_TARBALL_NAME }}
          tag: v4.0.0
